### ISSUE TITLE
UnityCam - normalization and unit measurements of depth map

### ISSUE THREAD

**Issue by jaruanob** [CapsuleEndoscope/VirtualCapsuleEndoscopy#5]
Hi, I'm writing to you to request more details about the normalization, unit measurements, and range of the depth ground truths, specifically of the UnityCAM images. I read the articles related to the library and database, but I didn't notice such information.

How should I interpret the relationship between the gray level values and the depth? Does each level correspond to 1 millimeter (I guess it is this option), 1 centimeter?

Or these depth maps have been normalized to some minimum and maximum depth values?

Thank you for your time, and I will be pending for your answer.

**Comment by inckagan** [comment]
Hi, please refer to AOV Image Sequence Recorder tool from Unity at the following link: https://docs.unity3d.com/Packages/com.unity.recorder@3.0/manual/RecorderAOV.html

As explained, depth values interpret the relative distances from 0 to 1.

![image](https://user-images.githubusercontent.com/25729477/128711164-8eee1148-007f-44ef-b452-9fdbf42ac1ec.png)

If you want to get actual depth values in cm, for example, you can use a technique called ray casting. Please refer to https://docs.unity3d.com/ScriptReference/Physics2D.Raycast.html

Hope this helps

**Comment by jaruanob** [comment]
Hi! @inckagan! thank you a lot for your answer!

But, my doubts about the normalization and unit measurements are specifically related to the details or configuration used in your environment (with Unity, etc ...) to generate the UnityCam sequences in the EndoSLAM dataset (https://github.com/CapsuleEndoscope/EndoSLAM). I am very interested in using this database to validate a depth estimation method, but I wish to have additional details, not present in the articles and the repository. I have three specific questions:

1. The RGB images and pixel-wise depths apparently are misalignment as showed @erezposner in this post (https://github.com/CapsuleEndoscope/EndoSLAM/issues/13).  I supposed the ground truth depth has some wide-angle lens distortion correction.

2. In the UnityCam folder, a calibration file is present (cam.txt) with this content

        156.0418,0,178.5604,0,155.7529,181.8043,0,0,1
    
    But, we don't know which means each value, we suppose this:

        fx: 156.0418,
        0, 
        cx: 178.5604,
        0, 
        fy: 155.7529,
        cy: 181.8043,
        skew:0,
    
        # Brown's distorsion model (radial components)?
        k1:0, k2:1
   
  Thank you whether you may clarify this.
   
3. With the previous questions, we wish to know, which are the linear (focal length, principal point, etc.) and nonlinear (refer to the distortion lens if there exist) intrinsic parameters of the camera used on the UnityCam set? 

It would help us to interpret the pixel-wise depth images of the database published.

Thank you a lot again, I will be pending.

**Comment by inckagan** [comment]
Hi,

1- We have used AOV Recorder tool for depth images and I checked the documentation but could not find any information regarding the correction. However, since we used some post-processing effects, as described, it is expected to have distorted RGB images.

2- Your assumption is correct. Please check below image.

3- Below image should answer that as well. We tried to mimic MiroCam (based on manufacturer data). Regarding distortion and other post-processing effects, we do not refer to any real camera.  We manually tuned them.

![image](https://user-images.githubusercontent.com/25729477/130767360-704c76e2-09e9-4f68-932c-b72b213f3f5b.png)

If you want pixel-wise depth images, I would suggest you to use our environment and generate new set with Raycasting algorithm I have previously posted.
